//Lanzamiento y captura de excepciones
/*
Una excepci贸n es un evento que ocurre durante la ejecuci贸n de un programa y que interrumpe el flujo normal del programa.
*/

void main() {
  try {
    int resultado = 10 ~/ 0; // Divisi贸n por cero
  } catch (e) {
    print('Error: $e');
  }
}

//Definici贸n de excepciones propias
/*
class EdadInvalidaException implements Exception {
  String causa;
  EdadInvalidaException(this.causa);
}

void verificarEdad(int edad) {
  if (edad < 0) {
    throw EdadInvalidaException('La edad no puede ser negativa');
  }
}

void main() {
  try {
    verificarEdad(-5);
  } catch (e) {
    print('Error: $e');
  }
}
*/